# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.33
# 

Name:       waypipe

# >> macros
# << macros
%define __meson_auto_features disabled
%define spectacle_bug hack_fix
%if 0%{?_chum}
BuildRequires: lz4-devel
%endif
%if 0%{?sailfishos_version} >= 40400
BuildRequires: pkgconfig(libzstd)
%define zstd_build enabled
%else
%define zstd_build disabled
%endif

Summary:    Network transparency with Wayland
Version:    0.10.2
Release:    0
Group:      Applications
License:    GPLv3
URL:        https://gitlab.freedesktop.org/mstoeckl/waypipe/
Source0:    %{name}-%{version}.tar.bz2
Source100:  waypipe.yaml
Source101:  waypipe-rpmlintrc
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(libavcodec)
BuildRequires:  pkgconfig(libavutil)
BuildRequires:  pkgconfig(libswscale)
BuildRequires:  sailfish-version > 3.2.1
BuildRequires:  cmake
BuildRequires:  meson
BuildRequires:  ninja

%description
waypipe is a proxy for Wayland clients.

It forwards Wayland messages and serializes changes to shared
memory buffers over a single socket. This makes application
forwarding similar to ssh -X feasible.

%if "%{?vendor}" == "chum"
Title: Waypipe
Type: console-application
DeveloperName: M. Stoeckl
PackagedBy: nephros
Categories:
 - Utility
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/sailfishos-chum/waypipe
  DescriptionMD: https://gitlab.freedesktop.org/mstoeckl/waypipe/-/raw/v0.9.2/README.md
PackageIcon: https://gitlab.freedesktop.org/uploads/-/system/project/avatar/3237/waypipe.png?width=128
Links:
  Homepage: https://mstoeckl.com/notes/gsoc/blog.html
  Help: https://forum.sailfishos.org/t/fun-with-remote-wayland-waypipe/16997
%endif


%package c
Summary:    Network transparency with Wayland
License:    MIT
Group:      Applications
Requires:   sailfish-version > 3.2.1
Provides:   waypipe-bin
Obsoletes:  waypipe <= 0.9.2
Obsoletes:  waypipe >= 0.8.6

%description c
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
#%%meson -Dwith_dmabuf=disabled -Dwith_vaapi=disabled -Dman-pages=disabled -Dwith_systemtap=false
#%%meson_build
%__meson setup %{_vpath_builddir} \
--buildtype=plain \
--prefix=%{_prefix} \
--libdir=%{_libdir} \
--libexecdir=%{_libexecdir} \
--bindir=%{_bindir} \
--sbindir=%{_sbindir} \
--includedir=%{_includedir} \
--datadir=%{_datadir} \
--mandir=%{_mandir} \
--infodir=%{_infodir} \
--localedir=%{_datadir}/locale \
--sysconfdir=%{_sysconfdir} \
--localstatedir=%{_localstatedir} \
--sharedstatedir=%{_sharedstatedir} \
--wrap-mode=%{__meson_wrap_mode} \
--auto-features=%{__meson_auto_features} \
-Dbuild_c=true \
-Dbuild_rs=false \
-Dtests=false \
-Dwith_video=enabled \
-Dwith_dmabuf=disabled \
-Dwith_vaapi=disabled \
-Dman-pages=disabled \
-Dwith_zstd=%{zstd_build} \
-Dwith_neon_opts=%{?arm64:true}%{!?arm64:false} \
-Dwith_lz4=%{?_chum:enabled}%{!?_chum:disabled} \
-Dwith_systemtap=false \
-Dwith_secctx=enabled \
%{nil}

pushd %{_vpath_builddir}
%ninja_build
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
#%%ninja_install -C build
%meson_install
# << install pre

# >> install post
# << install post


%files c
%defattr(-,root,root,-)
%license LICENSE.MIT
%{_bindir}/waypipe-c
# >> files c
# << files c
