# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.33
# 

Name:       waypipe

# >> macros
# << macros
%define __meson_auto_features disabled
%define spectacle_bug hack_fix
%if 0%{?_chum}
BuildRequires: lz4-devel
%endif
%if 0%{?sailfishos_version} >= 40400
BuildRequires: pkgconfig(libzstd)
%define zstd_build enabled
%else
%define zstd_build disabled
%endif

Summary:    Network transparency with Wayland
Version:    0.10.2
Release:    0
Group:      Applications
License:    MIT and GPLv3+
URL:        https://gitlab.freedesktop.org/mstoeckl/waypipe/
Source0:    %{name}-%{version}.tar.bz2
Source1:    vendor.tar.xz
Source100:  waypipe.yaml
Source101:  waypipe-rpmlintrc
Requires:   sailfish-version > 3.2.1
BuildRequires:  sailfish-version > 3.2.1
BuildRequires:  meson
BuildRequires:  ninja
BuildRequires:  ffmpeg-devel >= 3.1
BuildRequires:  cargo
BuildRequires:  rust >= 1.77.0

%description
waypipe is a proxy for Wayland clients.

It forwards Wayland messages and serializes changes to shared
memory buffers over a single socket. This makes application
forwarding similar to ssh -X feasible.

%if "%{?vendor}" == "chum"
Title: Waypipe
Type: console-application
DeveloperName: M. Stoeckl
PackagedBy: nephros
Categories:
 - Utility
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/sailfishos-chum/waypipe
  DescriptionMD: https://gitlab.freedesktop.org/mstoeckl/waypipe/-/raw/master/README.md
PackageIcon: https://gitlab.freedesktop.org/uploads/-/system/project/avatar/3237/waypipe.png?width=128
Links:
  Homepage: https://mstoeckl.com/notes/gsoc/blog.html
  Help: https://forum.sailfishos.org/t/fun-with-remote-wayland-waypipe/16997
  Bugtracker: https://github.com/sailfishos-chum/waypipe/issues
%endif


%prep
%setup -q -a1 -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# contains compiler definitions not applicable to SFOS:
mkdir -p .cargo
cat >> .cargo/config.toml <<EOF

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# Thanks, b100dian and others:
# https://forum.sailfishos.org/t/building-cargo-rust-software-on-community-obs/19409/5

%ifarch %arm32
%define SB2_TARGET armv7-unknown-linux-gnueabihf
%endif
%ifarch %arm64
%define SB2_TARGET aarch64-unknown-linux-gnu
%endif
%ifarch %ix86
%define SB2_TARGET i686-unknown-linux-gnu
%endif

export CARGO_BUILD_TARGET=%SB2_TARGET


# When cross-compiling under SB2 rust needs to know what arch to emit
# when nothing is specified on the command line. That usually defaults
# to "whatever rust was built as" but in SB2 rust is accelerated and
# would produce x86 so this is how it knows differently. Not needed
# for native x86 builds
export SB2_RUST_TARGET_TRIPLE=%SB2_TARGET
export RUST_HOST_TARGET=%SB2_TARGET

export RUST_TARGET=%SB2_TARGET
export TARGET=%SB2_TARGET
export HOST=%SB2_TARGET
export SB2_TARGET=%SB2_TARGET

%ifarch %arm32 %arm64
export CROSS_COMPILE=%SB2_TARGET

# This avoids a malloc hang in sb2 gated calls to execvp/dup2/chdir
# during fork/exec. It has no effect outside sb2 so doesn't hurt
# native builds.
export SB2_RUST_EXECVP_SHIM="/usr/bin/env LD_PRELOAD=/usr/lib/libsb2/libsb2.so.1 /usr/bin/env"
export SB2_RUST_USE_REAL_EXECVP=Yes
export SB2_RUST_USE_REAL_FN=Yes
%endif

export CC=gcc
export CXX=g++
export AR="ar"
export NM="gcc-nm"
export RANLIB="gcc-ranlib"
export PKG_CONFIG="pkg-config"

cargo build -vv --offline --release -j1


#%%meson -Dwith_dmabuf=disabled -Dwith_vaapi=disabled -Dman-pages=disabled -Dwith_systemtap=false
#%%meson_build
%__meson setup %{_vpath_builddir} \
--buildtype=plain \
--prefix=%{_prefix} \
--libdir=%{_libdir} \
--libexecdir=%{_libexecdir} \
--bindir=%{_bindir} \
--sbindir=%{_sbindir} \
--includedir=%{_includedir} \
--datadir=%{_datadir} \
--mandir=%{_mandir} \
--infodir=%{_infodir} \
--localedir=%{_datadir}/locale \
--sysconfdir=%{_sysconfdir} \
--localstatedir=%{_localstatedir} \
--sharedstatedir=%{_sharedstatedir} \
--wrap-mode=%{__meson_wrap_mode} \
--auto-features=%{__meson_auto_features} \
-Dwith_video=enabled \
-Dwith_dmabuf=disabled \
-Dwith_vaapi=disabled \
-Dman-pages=disabled \
-Dwith_zstd=%{zstd_build} \
-Dwith_neon_opts=%{?arm64:true}%{!?arm64:false} \
-Dwith_lz4=%{?_chum:enabled}%{!?_chum:disabled} \
-Dwith_systemtap=false
pushd %{_vpath_builddir}
%ninja_build
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
#%%ninja_install -C build
%meson_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/*
# >> files
# << files
